/// Flutter icons CustomIconsDataType
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIconsDataType
///      fonts:
///       - asset: fonts/CustomIconsDataType.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class CustomIconsDataType {
  CustomIconsDataType._();

  static const _kFontFam = 'CustomIconsDataType';
  static const String? _kFontPkg = null;

  static const IconData orders_bottom_nav_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tables_bottom_nav_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category_item_add_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData m = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xl = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category_item_remove_icon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
